title: ateanna uriri, professional semiprofessional.
description: working space to showcase finished projects and learn more about GitHub and programming languages.

[find me on wikipedia](https://en.wikipedia.org/wiki/User:Auriri)

theme: jekyll-theme-minimal
