title: ateanna uriri, professional semiprofessional.
description: work space to showcase (mostly) all my things and thoughts.

theme: jekyll-theme-minimal

plugins:
  - jemoji

# URL
url:                http://aouriri.github.io
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html
